server:
  port: 8082
  servlet:
    context-path: /price-list

#debug: enable


spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT-3
  application:
    name: core-price
  datasource:
    url: jdbc:h2:mem:price-db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: challenge
    password: challenge

  flyway:
    user: challenge
    password: challenge
    url: jdbc:h2:mem:price-db
    #    locations: classpath:../../../../config/db.migration
    enabled: true

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2/h2-console
      settings:
        trace: false
        web-allow-others: true

management:
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

challenge:
  app:
    jwtSecret: capitole-secret-key
    jwtExpirationMs: 86400000